// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/rpc/instance.proto

package teleporter.integration.cluster.rpc.proto.instance;

public final class Instance {
  private Instance() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigChangeNotifyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string key = 1;</code>
     */
    java.lang.String getKey();
    /**
     * <code>optional string key = 1;</code>
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
     */
    int getActionValue();
    /**
     * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
     */
    teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action getAction();

    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify}
   */
  public  static final class ConfigChangeNotify extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify)
      ConfigChangeNotifyOrBuilder {
    // Use ConfigChangeNotify.newBuilder() to construct.
    private ConfigChangeNotify(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConfigChangeNotify() {
      key_ = "";
      action_ = 0;
      timestamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ConfigChangeNotify(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              key_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            case 24: {

              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.class, teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Builder.class);
    }

    /**
     * Protobuf enum {@code teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action}
     */
    public enum Action
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 0;</code>
       */
      ADD(0),
      /**
       * <code>UPDATE = 1;</code>
       */
      UPDATE(1),
      /**
       * <code>UPSERT = 2;</code>
       */
      UPSERT(2),
      /**
       * <code>REMOVE = 3;</code>
       */
      REMOVE(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ADD = 0;</code>
       */
      public static final int ADD_VALUE = 0;
      /**
       * <code>UPDATE = 1;</code>
       */
      public static final int UPDATE_VALUE = 1;
      /**
       * <code>UPSERT = 2;</code>
       */
      public static final int UPSERT_VALUE = 2;
      /**
       * <code>REMOVE = 3;</code>
       */
      public static final int REMOVE_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Action valueOf(int value) {
        return forNumber(value);
      }

      public static Action forNumber(int value) {
        switch (value) {
          case 0: return ADD;
          case 1: return UPDATE;
          case 2: return UPSERT;
          case 3: return REMOVE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Action>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Action> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Action>() {
              public Action findValueByNumber(int number) {
                return Action.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.getDescriptor().getEnumTypes().get(0);
      }

      private static final Action[] VALUES = values();

      public static Action valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Action(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action)
    }

    public static final int KEY_FIELD_NUMBER = 1;
    private volatile java.lang.Object key_;
    /**
     * <code>optional string key = 1;</code>
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      }
    }
    /**
     * <code>optional string key = 1;</code>
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
     */
    public int getActionValue() {
      return action_;
    }
    /**
     * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
     */
    public teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action getAction() {
      teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action result = teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action.valueOf(action_);
      return result == null ? teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action.UNRECOGNIZED : result;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
      }
      if (action_ != teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action.ADD.getNumber()) {
        output.writeEnum(2, action_);
      }
      if (timestamp_ != 0L) {
        output.writeInt64(3, timestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
      }
      if (action_ != teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action.ADD.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify)) {
        return super.equals(obj);
      }
      teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify other = (teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify) obj;

      boolean result = true;
      result = result && getKey()
          .equals(other.getKey());
      result = result && action_ == other.action_;
      result = result && (getTimestamp()
          == other.getTimestamp());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify)
        teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotifyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.class, teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Builder.class);
      }

      // Construct using teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        key_ = "";

        action_ = 0;

        timestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_descriptor;
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify getDefaultInstanceForType() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.getDefaultInstance();
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify build() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify buildPartial() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify result = new teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify(this);
        result.key_ = key_;
        result.action_ = action_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify) {
          return mergeFrom((teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify other) {
        if (other == teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.getDefaultInstance()) return this;
        if (!other.getKey().isEmpty()) {
          key_ = other.key_;
          onChanged();
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>optional string key = 1;</code>
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          key_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder clearKey() {
        
        key_ = getDefaultInstance().getKey();
        onChanged();
        return this;
      }
      /**
       * <code>optional string key = 1;</code>
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        key_ = value;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
       */
      public int getActionValue() {
        return action_;
      }
      /**
       * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
       */
      public Builder setActionValue(int value) {
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
       */
      public teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action getAction() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action result = teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action.valueOf(action_);
        return result == null ? teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
       */
      public Builder setAction(teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify.Action action = 2;</code>
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify)
    }

    // @@protoc_insertion_point(class_scope:teleporter.integration.cluster.rpc.proto.instance.ConfigChangeNotify)
    private static final teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify();
    }

    public static teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConfigChangeNotify>
        PARSER = new com.google.protobuf.AbstractParser<ConfigChangeNotify>() {
      public ConfigChangeNotify parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ConfigChangeNotify(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConfigChangeNotify> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConfigChangeNotify> getParserForType() {
      return PARSER;
    }

    public teleporter.integration.cluster.rpc.proto.instance.Instance.ConfigChangeNotify getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:teleporter.integration.cluster.rpc.proto.instance.HealthResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional float totalMemory = 1;</code>
     */
    float getTotalMemory();

    /**
     * <code>optional float freeMemory = 2;</code>
     */
    float getFreeMemory();
  }
  /**
   * Protobuf type {@code teleporter.integration.cluster.rpc.proto.instance.HealthResponse}
   */
  public  static final class HealthResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:teleporter.integration.cluster.rpc.proto.instance.HealthResponse)
      HealthResponseOrBuilder {
    // Use HealthResponse.newBuilder() to construct.
    private HealthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthResponse() {
      totalMemory_ = 0F;
      freeMemory_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private HealthResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 13: {

              totalMemory_ = input.readFloat();
              break;
            }
            case 21: {

              freeMemory_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.class, teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.Builder.class);
    }

    public static final int TOTALMEMORY_FIELD_NUMBER = 1;
    private float totalMemory_;
    /**
     * <code>optional float totalMemory = 1;</code>
     */
    public float getTotalMemory() {
      return totalMemory_;
    }

    public static final int FREEMEMORY_FIELD_NUMBER = 2;
    private float freeMemory_;
    /**
     * <code>optional float freeMemory = 2;</code>
     */
    public float getFreeMemory() {
      return freeMemory_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (totalMemory_ != 0F) {
        output.writeFloat(1, totalMemory_);
      }
      if (freeMemory_ != 0F) {
        output.writeFloat(2, freeMemory_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (totalMemory_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, totalMemory_);
      }
      if (freeMemory_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, freeMemory_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse)) {
        return super.equals(obj);
      }
      teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse other = (teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getTotalMemory())
          == java.lang.Float.floatToIntBits(
              other.getTotalMemory()));
      result = result && (
          java.lang.Float.floatToIntBits(getFreeMemory())
          == java.lang.Float.floatToIntBits(
              other.getFreeMemory()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TOTALMEMORY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTotalMemory());
      hash = (37 * hash) + FREEMEMORY_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFreeMemory());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code teleporter.integration.cluster.rpc.proto.instance.HealthResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:teleporter.integration.cluster.rpc.proto.instance.HealthResponse)
        teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.class, teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.Builder.class);
      }

      // Construct using teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        totalMemory_ = 0F;

        freeMemory_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_descriptor;
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse getDefaultInstanceForType() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.getDefaultInstance();
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse build() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse buildPartial() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse result = new teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse(this);
        result.totalMemory_ = totalMemory_;
        result.freeMemory_ = freeMemory_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse) {
          return mergeFrom((teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse other) {
        if (other == teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse.getDefaultInstance()) return this;
        if (other.getTotalMemory() != 0F) {
          setTotalMemory(other.getTotalMemory());
        }
        if (other.getFreeMemory() != 0F) {
          setFreeMemory(other.getFreeMemory());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float totalMemory_ ;
      /**
       * <code>optional float totalMemory = 1;</code>
       */
      public float getTotalMemory() {
        return totalMemory_;
      }
      /**
       * <code>optional float totalMemory = 1;</code>
       */
      public Builder setTotalMemory(float value) {
        
        totalMemory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float totalMemory = 1;</code>
       */
      public Builder clearTotalMemory() {
        
        totalMemory_ = 0F;
        onChanged();
        return this;
      }

      private float freeMemory_ ;
      /**
       * <code>optional float freeMemory = 2;</code>
       */
      public float getFreeMemory() {
        return freeMemory_;
      }
      /**
       * <code>optional float freeMemory = 2;</code>
       */
      public Builder setFreeMemory(float value) {
        
        freeMemory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float freeMemory = 2;</code>
       */
      public Builder clearFreeMemory() {
        
        freeMemory_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:teleporter.integration.cluster.rpc.proto.instance.HealthResponse)
    }

    // @@protoc_insertion_point(class_scope:teleporter.integration.cluster.rpc.proto.instance.HealthResponse)
    private static final teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse();
    }

    public static teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthResponse>
        PARSER = new com.google.protobuf.AbstractParser<HealthResponse>() {
      public HealthResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HealthResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthResponse> getParserForType() {
      return PARSER;
    }

    public teleporter.integration.cluster.rpc.proto.instance.Instance.HealthResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:teleporter.integration.cluster.rpc.proto.instance.LogResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string line = 1;</code>
     */
    java.lang.String getLine();
    /**
     * <code>optional string line = 1;</code>
     */
    com.google.protobuf.ByteString
        getLineBytes();
  }
  /**
   * Protobuf type {@code teleporter.integration.cluster.rpc.proto.instance.LogResponse}
   */
  public  static final class LogResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:teleporter.integration.cluster.rpc.proto.instance.LogResponse)
      LogResponseOrBuilder {
    // Use LogResponse.newBuilder() to construct.
    private LogResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogResponse() {
      line_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              line_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.class, teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.Builder.class);
    }

    public static final int LINE_FIELD_NUMBER = 1;
    private volatile java.lang.Object line_;
    /**
     * <code>optional string line = 1;</code>
     */
    public java.lang.String getLine() {
      java.lang.Object ref = line_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        line_ = s;
        return s;
      }
    }
    /**
     * <code>optional string line = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLineBytes() {
      java.lang.Object ref = line_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        line_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLineBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, line_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLineBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, line_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse)) {
        return super.equals(obj);
      }
      teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse other = (teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse) obj;

      boolean result = true;
      result = result && getLine()
          .equals(other.getLine());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + LINE_FIELD_NUMBER;
      hash = (53 * hash) + getLine().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code teleporter.integration.cluster.rpc.proto.instance.LogResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:teleporter.integration.cluster.rpc.proto.instance.LogResponse)
        teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.class, teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.Builder.class);
      }

      // Construct using teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        line_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_descriptor;
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse getDefaultInstanceForType() {
        return teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.getDefaultInstance();
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse build() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse buildPartial() {
        teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse result = new teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse(this);
        result.line_ = line_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse) {
          return mergeFrom((teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse other) {
        if (other == teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse.getDefaultInstance()) return this;
        if (!other.getLine().isEmpty()) {
          line_ = other.line_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object line_ = "";
      /**
       * <code>optional string line = 1;</code>
       */
      public java.lang.String getLine() {
        java.lang.Object ref = line_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          line_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string line = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLineBytes() {
        java.lang.Object ref = line_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          line_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string line = 1;</code>
       */
      public Builder setLine(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        line_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string line = 1;</code>
       */
      public Builder clearLine() {
        
        line_ = getDefaultInstance().getLine();
        onChanged();
        return this;
      }
      /**
       * <code>optional string line = 1;</code>
       */
      public Builder setLineBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        line_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:teleporter.integration.cluster.rpc.proto.instance.LogResponse)
    }

    // @@protoc_insertion_point(class_scope:teleporter.integration.cluster.rpc.proto.instance.LogResponse)
    private static final teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse();
    }

    public static teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogResponse>
        PARSER = new com.google.protobuf.AbstractParser<LogResponse>() {
      public LogResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogResponse> getParserForType() {
      return PARSER;
    }

    public teleporter.integration.cluster.rpc.proto.instance.Instance.LogResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/rpc/instance.proto\0221teleporter.i" +
      "ntegration.cluster.rpc.proto.instance\"\311\001" +
      "\n\022ConfigChangeNotify\022\013\n\003key\030\001 \001(\t\022\\\n\006act" +
      "ion\030\002 \001(\0162L.teleporter.integration.clust" +
      "er.rpc.proto.instance.ConfigChangeNotify" +
      ".Action\022\021\n\ttimestamp\030\003 \001(\003\"5\n\006Action\022\007\n\003" +
      "ADD\020\000\022\n\n\006UPDATE\020\001\022\n\n\006UPSERT\020\002\022\n\n\006REMOVE\020" +
      "\003\"9\n\016HealthResponse\022\023\n\013totalMemory\030\001 \001(\002" +
      "\022\022\n\nfreeMemory\030\002 \001(\002\"\033\n\013LogResponse\022\014\n\004l" +
      "ine\030\001 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teleporter_integration_cluster_rpc_proto_instance_ConfigChangeNotify_descriptor,
        new java.lang.String[] { "Key", "Action", "Timestamp", });
    internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teleporter_integration_cluster_rpc_proto_instance_HealthResponse_descriptor,
        new java.lang.String[] { "TotalMemory", "FreeMemory", });
    internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_teleporter_integration_cluster_rpc_proto_instance_LogResponse_descriptor,
        new java.lang.String[] { "Line", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
