// automatically generated by the FlatBuffers compiler, do not modify

package teleporter.integration.cluster.rpc.fbs.generate.instance;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LogResponse extends Table {
  public static LogResponse getRootAsLogResponse(ByteBuffer _bb) { return getRootAsLogResponse(_bb, new LogResponse()); }
  public static LogResponse getRootAsLogResponse(ByteBuffer _bb, LogResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LogResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String line() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lineAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createLogResponse(FlatBufferBuilder builder,
      int lineOffset) {
    builder.startObject(1);
    LogResponse.addLine(builder, lineOffset);
    return LogResponse.endLogResponse(builder);
  }

  public static void startLogResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addLine(FlatBufferBuilder builder, int lineOffset) { builder.addOffset(0, lineOffset, 0); }
  public static int endLogResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

