// automatically generated by the FlatBuffers compiler, do not modify

package teleporter.integration.cluster.rpc.fbs;

public final class EventStatus {
    private EventStatus() {
    }

    public static final byte Failure = 0;
    public static final byte Success = 1;
    public static final byte None = 2;

    public static final String[] names = {"Failure", "Success", "None",};

    public static String name(int e) {
        return names[e];
    }
}

