// automatically generated by the FlatBuffers compiler, do not modify

package teleporter.integration.cluster.rpc.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class LogTailResponse extends Table {
  public static LogTailResponse getRootAsLogTailResponse(ByteBuffer _bb) { return getRootAsLogTailResponse(_bb, new LogTailResponse()); }
  public static LogTailResponse getRootAsLogTailResponse(ByteBuffer _bb, LogTailResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public LogTailResponse __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String line() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer lineAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createLogTailResponse(FlatBufferBuilder builder,
      int lineOffset) {
    builder.startObject(1);
    LogTailResponse.addLine(builder, lineOffset);
    return LogTailResponse.endLogTailResponse(builder);
  }

  public static void startLogTailResponse(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addLine(FlatBufferBuilder builder, int lineOffset) { builder.addOffset(0, lineOffset, 0); }
  public static int endLogTailResponse(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

