// automatically generated by the FlatBuffers compiler, do not modify

package teleporter.integration.cluster.rpc.fbs;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class RpcMessage extends Table {
  public static RpcMessage getRootAsRpcMessage(ByteBuffer _bb) { return getRootAsRpcMessage(_bb, new RpcMessage()); }
  public static RpcMessage getRootAsRpcMessage(ByteBuffer _bb, RpcMessage obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public RpcMessage __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public long seqNr() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0; }
  public byte messageType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte role() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte status() { int o = __offset(10); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte body(int j) { int o = __offset(12); return o != 0 ? bb.get(__vector(o) + j * 1) : 0; }
  public int bodyLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public ByteBuffer bodyAsByteBuffer() { return __vector_as_bytebuffer(12, 1); }

  public static int createRpcMessage(FlatBufferBuilder builder,
      long seqNr,
      byte messageType,
      byte role,
      byte status,
      int bodyOffset) {
    builder.startObject(5);
    RpcMessage.addSeqNr(builder, seqNr);
    RpcMessage.addBody(builder, bodyOffset);
    RpcMessage.addStatus(builder, status);
    RpcMessage.addRole(builder, role);
    RpcMessage.addMessageType(builder, messageType);
    return RpcMessage.endRpcMessage(builder);
  }

  public static void startRpcMessage(FlatBufferBuilder builder) { builder.startObject(5); }
  public static void addSeqNr(FlatBufferBuilder builder, long seqNr) { builder.addLong(0, seqNr, 0); }
  public static void addMessageType(FlatBufferBuilder builder, byte messageType) { builder.addByte(1, messageType, 0); }
  public static void addRole(FlatBufferBuilder builder, byte role) { builder.addByte(2, role, 0); }
  public static void addStatus(FlatBufferBuilder builder, byte status) { builder.addByte(3, status, 0); }
  public static void addBody(FlatBufferBuilder builder, int bodyOffset) { builder.addOffset(4, bodyOffset, 0); }
  public static int createBodyVector(FlatBufferBuilder builder, byte[] data) { builder.startVector(1, data.length, 1); for (int i = data.length - 1; i >= 0; i--) builder.addByte(data[i]); return builder.endVector(); }
  public static void startBodyVector(FlatBufferBuilder builder, int numElems) { builder.startVector(1, numElems, 1); }
  public static int endRpcMessage(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

