// automatically generated by the FlatBuffers compiler, do not modify

package teleporter.integration.cluster.rpc.fbs.generate.broker;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class KVRemove extends Table {
  public static KVRemove getRootAsKVRemove(ByteBuffer _bb) { return getRootAsKVRemove(_bb, new KVRemove()); }
  public static KVRemove getRootAsKVRemove(ByteBuffer _bb, KVRemove obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__init(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public KVRemove __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; return this; }

  public String key() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer keyAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createKVRemove(FlatBufferBuilder builder,
      int keyOffset) {
    builder.startObject(1);
    KVRemove.addKey(builder, keyOffset);
    return KVRemove.endKVRemove(builder);
  }

  public static void startKVRemove(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addKey(FlatBufferBuilder builder, int keyOffset) { builder.addOffset(0, keyOffset, 0); }
  public static int endKVRemove(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

