// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_buf.proto

package teleporter.integration.protocol.proto;

public final class FileBuf {
    private FileBuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface FileProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:teleporter.integration.proto.FileProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bytes tId = 1;</code>
         */
        boolean hasTId();

        /**
         * <code>required bytes tId = 1;</code>
         */
        com.google.protobuf.ByteString getTId();

        /**
         * <code>required string filePath = 2;</code>
         */
        boolean hasFilePath();

        /**
         * <code>required string filePath = 2;</code>
         */
        String getFilePath();

        /**
         * <code>required string filePath = 2;</code>
         */
        com.google.protobuf.ByteString
        getFilePathBytes();

        /**
         * <code>required bool append = 3;</code>
         */
        boolean hasAppend();

        /**
         * <code>required bool append = 3;</code>
         */
        boolean getAppend();

        /**
         * <code>required bytes message = 4;</code>
         */
        boolean hasMessage();

        /**
         * <code>required bytes message = 4;</code>
         */
        com.google.protobuf.ByteString getMessage();

        /**
         * <code>required int64 position = 5;</code>
         */
        boolean hasPosition();

        /**
         * <code>required int64 position = 5;</code>
         */
        long getPosition();
    }

    /**
     * Protobuf type {@code teleporter.integration.proto.FileProto}
     */
    public static final class FileProto extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:teleporter.integration.proto.FileProto)
            FileProtoOrBuilder {
        // Use FileProto.newBuilder() to construct.
        private FileProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private FileProto(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final FileProto defaultInstance;

        public static FileProto getDefaultInstance() {
            return defaultInstance;
        }

        public FileProto getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private FileProto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            tId_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            filePath_ = bs;
                            break;
                        }
                        case 24: {
                            bitField0_ |= 0x00000004;
                            append_ = input.readBool();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            message_ = input.readBytes();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            position_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return FileBuf.internal_static_teleporter_integration_proto_FileProto_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return FileBuf.internal_static_teleporter_integration_proto_FileProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            FileProto.class, Builder.class);
        }

        public static com.google.protobuf.Parser<FileProto> PARSER =
                new com.google.protobuf.AbstractParser<FileProto>() {
                    public FileProto parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new FileProto(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<FileProto> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int TID_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString tId_;

        /**
         * <code>required bytes tId = 1;</code>
         */
        public boolean hasTId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bytes tId = 1;</code>
         */
        public com.google.protobuf.ByteString getTId() {
            return tId_;
        }

        public static final int FILEPATH_FIELD_NUMBER = 2;
        private Object filePath_;

        /**
         * <code>required string filePath = 2;</code>
         */
        public boolean hasFilePath() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string filePath = 2;</code>
         */
        public String getFilePath() {
            Object ref = filePath_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    filePath_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string filePath = 2;</code>
         */
        public com.google.protobuf.ByteString
        getFilePathBytes() {
            Object ref = filePath_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                filePath_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int APPEND_FIELD_NUMBER = 3;
        private boolean append_;

        /**
         * <code>required bool append = 3;</code>
         */
        public boolean hasAppend() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required bool append = 3;</code>
         */
        public boolean getAppend() {
            return append_;
        }

        public static final int MESSAGE_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString message_;

        /**
         * <code>required bytes message = 4;</code>
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required bytes message = 4;</code>
         */
        public com.google.protobuf.ByteString getMessage() {
            return message_;
        }

        public static final int POSITION_FIELD_NUMBER = 5;
        private long position_;

        /**
         * <code>required int64 position = 5;</code>
         */
        public boolean hasPosition() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>required int64 position = 5;</code>
         */
        public long getPosition() {
            return position_;
        }

        private void initFields() {
            tId_ = com.google.protobuf.ByteString.EMPTY;
            filePath_ = "";
            append_ = false;
            message_ = com.google.protobuf.ByteString.EMPTY;
            position_ = 0L;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasTId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasFilePath()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasAppend()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasPosition()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, tId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getFilePathBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBool(3, append_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, message_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeInt64(5, position_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, tId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getFilePathBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(3, append_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, message_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(5, position_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static FileProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static FileProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static FileProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static FileProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static FileProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static FileProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(FileProto prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code teleporter.integration.proto.FileProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:teleporter.integration.proto.FileProto)
                FileProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return FileBuf.internal_static_teleporter_integration_proto_FileProto_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return FileBuf.internal_static_teleporter_integration_proto_FileProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                FileProto.class, Builder.class);
            }

            // Construct using teleporter.integration.proto.FileBuf.FileProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                tId_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                filePath_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                append_ = false;
                bitField0_ = (bitField0_ & ~0x00000004);
                message_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000008);
                position_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return FileBuf.internal_static_teleporter_integration_proto_FileProto_descriptor;
            }

            public FileProto getDefaultInstanceForType() {
                return FileProto.getDefaultInstance();
            }

            public FileProto build() {
                FileProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public FileProto buildPartial() {
                FileProto result = new FileProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.tId_ = tId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.filePath_ = filePath_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.append_ = append_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.message_ = message_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.position_ = position_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof FileProto) {
                    return mergeFrom((FileProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(FileProto other) {
                if (other == FileProto.getDefaultInstance()) return this;
                if (other.hasTId()) {
                    setTId(other.getTId());
                }
                if (other.hasFilePath()) {
                    bitField0_ |= 0x00000002;
                    filePath_ = other.filePath_;
                    onChanged();
                }
                if (other.hasAppend()) {
                    setAppend(other.getAppend());
                }
                if (other.hasMessage()) {
                    setMessage(other.getMessage());
                }
                if (other.hasPosition()) {
                    setPosition(other.getPosition());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasTId()) {

                    return false;
                }
                if (!hasFilePath()) {

                    return false;
                }
                if (!hasAppend()) {

                    return false;
                }
                if (!hasMessage()) {

                    return false;
                }
                if (!hasPosition()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                FileProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (FileProto) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString tId_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes tId = 1;</code>
             */
            public boolean hasTId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bytes tId = 1;</code>
             */
            public com.google.protobuf.ByteString getTId() {
                return tId_;
            }

            /**
             * <code>required bytes tId = 1;</code>
             */
            public Builder setTId(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                tId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes tId = 1;</code>
             */
            public Builder clearTId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                tId_ = getDefaultInstance().getTId();
                onChanged();
                return this;
            }

            private Object filePath_ = "";

            /**
             * <code>required string filePath = 2;</code>
             */
            public boolean hasFilePath() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string filePath = 2;</code>
             */
            public String getFilePath() {
                Object ref = filePath_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        filePath_ = s;
                    }
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string filePath = 2;</code>
             */
            public com.google.protobuf.ByteString
            getFilePathBytes() {
                Object ref = filePath_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    filePath_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string filePath = 2;</code>
             */
            public Builder setFilePath(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                filePath_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string filePath = 2;</code>
             */
            public Builder clearFilePath() {
                bitField0_ = (bitField0_ & ~0x00000002);
                filePath_ = getDefaultInstance().getFilePath();
                onChanged();
                return this;
            }

            /**
             * <code>required string filePath = 2;</code>
             */
            public Builder setFilePathBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                filePath_ = value;
                onChanged();
                return this;
            }

            private boolean append_;

            /**
             * <code>required bool append = 3;</code>
             */
            public boolean hasAppend() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required bool append = 3;</code>
             */
            public boolean getAppend() {
                return append_;
            }

            /**
             * <code>required bool append = 3;</code>
             */
            public Builder setAppend(boolean value) {
                bitField0_ |= 0x00000004;
                append_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool append = 3;</code>
             */
            public Builder clearAppend() {
                bitField0_ = (bitField0_ & ~0x00000004);
                append_ = false;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes message = 4;</code>
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required bytes message = 4;</code>
             */
            public com.google.protobuf.ByteString getMessage() {
                return message_;
            }

            /**
             * <code>required bytes message = 4;</code>
             */
            public Builder setMessage(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes message = 4;</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000008);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            private long position_;

            /**
             * <code>required int64 position = 5;</code>
             */
            public boolean hasPosition() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>required int64 position = 5;</code>
             */
            public long getPosition() {
                return position_;
            }

            /**
             * <code>required int64 position = 5;</code>
             */
            public Builder setPosition(long value) {
                bitField0_ |= 0x00000010;
                position_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int64 position = 5;</code>
             */
            public Builder clearPosition() {
                bitField0_ = (bitField0_ & ~0x00000010);
                position_ = 0L;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:teleporter.integration.proto.FileProto)
        }

        static {
            defaultInstance = new FileProto(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:teleporter.integration.proto.FileProto)
    }

    public interface FileProtosOrBuilder extends
            // @@protoc_insertion_point(interface_extends:teleporter.integration.proto.FileProtos)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        java.util.List<FileProto>
        getProtosList();

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        FileProto getProtos(int index);

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        int getProtosCount();

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        java.util.List<? extends FileProtoOrBuilder>
        getProtosOrBuilderList();

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        FileProtoOrBuilder getProtosOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code teleporter.integration.proto.FileProtos}
     */
    public static final class FileProtos extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:teleporter.integration.proto.FileProtos)
            FileProtosOrBuilder {
        // Use FileProtos.newBuilder() to construct.
        private FileProtos(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private FileProtos(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final FileProtos defaultInstance;

        public static FileProtos getDefaultInstance() {
            return defaultInstance;
        }

        public FileProtos getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private FileProtos(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                protos_ = new java.util.ArrayList<FileProto>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            protos_.add(input.readMessage(FileProto.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    protos_ = java.util.Collections.unmodifiableList(protos_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return FileBuf.internal_static_teleporter_integration_proto_FileProtos_descriptor;
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return FileBuf.internal_static_teleporter_integration_proto_FileProtos_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            FileProtos.class, Builder.class);
        }

        public static com.google.protobuf.Parser<FileProtos> PARSER =
                new com.google.protobuf.AbstractParser<FileProtos>() {
                    public FileProtos parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new FileProtos(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<FileProtos> getParserForType() {
            return PARSER;
        }

        public static final int PROTOS_FIELD_NUMBER = 1;
        private java.util.List<FileProto> protos_;

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        public java.util.List<FileProto> getProtosList() {
            return protos_;
        }

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        public java.util.List<? extends FileProtoOrBuilder>
        getProtosOrBuilderList() {
            return protos_;
        }

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        public int getProtosCount() {
            return protos_.size();
        }

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        public FileProto getProtos(int index) {
            return protos_.get(index);
        }

        /**
         * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
         */
        public FileProtoOrBuilder getProtosOrBuilder(
                int index) {
            return protos_.get(index);
        }

        private void initFields() {
            protos_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            for (int i = 0; i < getProtosCount(); i++) {
                if (!getProtos(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < protos_.size(); i++) {
                output.writeMessage(1, protos_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < protos_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, protos_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static FileProtos parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileProtos parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileProtos parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static FileProtos parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static FileProtos parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static FileProtos parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static FileProtos parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static FileProtos parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static FileProtos parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static FileProtos parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(FileProtos prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code teleporter.integration.proto.FileProtos}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:teleporter.integration.proto.FileProtos)
                FileProtosOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return FileBuf.internal_static_teleporter_integration_proto_FileProtos_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return FileBuf.internal_static_teleporter_integration_proto_FileProtos_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                FileProtos.class, Builder.class);
            }

            // Construct using teleporter.integration.proto.FileBuf.FileProtos.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getProtosFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                if (protosBuilder_ == null) {
                    protos_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    protosBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return FileBuf.internal_static_teleporter_integration_proto_FileProtos_descriptor;
            }

            public FileProtos getDefaultInstanceForType() {
                return FileProtos.getDefaultInstance();
            }

            public FileProtos build() {
                FileProtos result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public FileProtos buildPartial() {
                FileProtos result = new FileProtos(this);
                int from_bitField0_ = bitField0_;
                if (protosBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        protos_ = java.util.Collections.unmodifiableList(protos_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.protos_ = protos_;
                } else {
                    result.protos_ = protosBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof FileProtos) {
                    return mergeFrom((FileProtos) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(FileProtos other) {
                if (other == FileProtos.getDefaultInstance()) return this;
                if (protosBuilder_ == null) {
                    if (!other.protos_.isEmpty()) {
                        if (protos_.isEmpty()) {
                            protos_ = other.protos_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureProtosIsMutable();
                            protos_.addAll(other.protos_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.protos_.isEmpty()) {
                        if (protosBuilder_.isEmpty()) {
                            protosBuilder_.dispose();
                            protosBuilder_ = null;
                            protos_ = other.protos_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            protosBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getProtosFieldBuilder() : null;
                        } else {
                            protosBuilder_.addAllMessages(other.protos_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                for (int i = 0; i < getProtosCount(); i++) {
                    if (!getProtos(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                FileProtos parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (FileProtos) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.util.List<FileProto> protos_ =
                    java.util.Collections.emptyList();

            private void ensureProtosIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    protos_ = new java.util.ArrayList<FileProto>(protos_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    FileProto, FileProto.Builder, FileProtoOrBuilder> protosBuilder_;

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public java.util.List<FileProto> getProtosList() {
                if (protosBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(protos_);
                } else {
                    return protosBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public int getProtosCount() {
                if (protosBuilder_ == null) {
                    return protos_.size();
                } else {
                    return protosBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public FileProto getProtos(int index) {
                if (protosBuilder_ == null) {
                    return protos_.get(index);
                } else {
                    return protosBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder setProtos(
                    int index, FileProto value) {
                if (protosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureProtosIsMutable();
                    protos_.set(index, value);
                    onChanged();
                } else {
                    protosBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder setProtos(
                    int index, FileProto.Builder builderForValue) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    protosBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder addProtos(FileProto value) {
                if (protosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureProtosIsMutable();
                    protos_.add(value);
                    onChanged();
                } else {
                    protosBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder addProtos(
                    int index, FileProto value) {
                if (protosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureProtosIsMutable();
                    protos_.add(index, value);
                    onChanged();
                } else {
                    protosBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder addProtos(
                    FileProto.Builder builderForValue) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.add(builderForValue.build());
                    onChanged();
                } else {
                    protosBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder addProtos(
                    int index, FileProto.Builder builderForValue) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    protosBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder addAllProtos(
                    Iterable<? extends FileProto> values) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, protos_);
                    onChanged();
                } else {
                    protosBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder clearProtos() {
                if (protosBuilder_ == null) {
                    protos_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    protosBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public Builder removeProtos(int index) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.remove(index);
                    onChanged();
                } else {
                    protosBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public FileProto.Builder getProtosBuilder(
                    int index) {
                return getProtosFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public FileProtoOrBuilder getProtosOrBuilder(
                    int index) {
                if (protosBuilder_ == null) {
                    return protos_.get(index);
                } else {
                    return protosBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public java.util.List<? extends FileProtoOrBuilder>
            getProtosOrBuilderList() {
                if (protosBuilder_ != null) {
                    return protosBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(protos_);
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public FileProto.Builder addProtosBuilder() {
                return getProtosFieldBuilder().addBuilder(
                        FileProto.getDefaultInstance());
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public FileProto.Builder addProtosBuilder(
                    int index) {
                return getProtosFieldBuilder().addBuilder(
                        index, FileProto.getDefaultInstance());
            }

            /**
             * <code>repeated .teleporter.integration.proto.FileProto protos = 1;</code>
             */
            public java.util.List<FileProto.Builder>
            getProtosBuilderList() {
                return getProtosFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    FileProto, FileProto.Builder, FileProtoOrBuilder>
            getProtosFieldBuilder() {
                if (protosBuilder_ == null) {
                    protosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            FileProto, FileProto.Builder, FileProtoOrBuilder>(
                            protos_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    protos_ = null;
                }
                return protosBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:teleporter.integration.proto.FileProtos)
        }

        static {
            defaultInstance = new FileProtos(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:teleporter.integration.proto.FileProtos)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_teleporter_integration_proto_FileProto_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_teleporter_integration_proto_FileProto_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_teleporter_integration_proto_FileProtos_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_teleporter_integration_proto_FileProtos_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\016file_buf.proto\022\034teleporter.integration" +
                        ".proto\"]\n\tFileProto\022\013\n\003tId\030\001 \002(\014\022\020\n\010file" +
                        "Path\030\002 \002(\t\022\016\n\006append\030\003 \002(\010\022\017\n\007message\030\004 " +
                        "\002(\014\022\020\n\010position\030\005 \002(\003\"E\n\nFileProtos\0227\n\006p" +
                        "rotos\030\001 \003(\0132\'.teleporter.integration.pro" +
                        "to.FileProto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_teleporter_integration_proto_FileProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_teleporter_integration_proto_FileProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_teleporter_integration_proto_FileProto_descriptor,
                new String[]{"TId", "FilePath", "Append", "Message", "Position",});
        internal_static_teleporter_integration_proto_FileProtos_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_teleporter_integration_proto_FileProtos_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_teleporter_integration_proto_FileProtos_descriptor,
                new String[]{"Protos",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
