// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/kafka_buf.proto

package teleporter.integration.protocol.proto;

public final class KafkaBuf {
    private KafkaBuf() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface KafkaProtoOrBuilder extends
            // @@protoc_insertion_point(interface_extends:teleporter.integration.proto.KafkaProto)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required bytes tId = 1;</code>
         */
        boolean hasTId();

        /**
         * <code>required bytes tId = 1;</code>
         */
        com.google.protobuf.ByteString getTId();

        /**
         * <code>required string topic = 2;</code>
         */
        boolean hasTopic();

        /**
         * <code>required string topic = 2;</code>
         */
        java.lang.String getTopic();

        /**
         * <code>required string topic = 2;</code>
         */
        com.google.protobuf.ByteString
        getTopicBytes();

        /**
         * <code>required bytes key = 3;</code>
         */
        boolean hasKey();

        /**
         * <code>required bytes key = 3;</code>
         */
        com.google.protobuf.ByteString getKey();

        /**
         * <code>required int32 partition = 4;</code>
         */
        boolean hasPartition();

        /**
         * <code>required int32 partition = 4;</code>
         */
        int getPartition();

        /**
         * <code>required bytes message = 5;</code>
         */
        boolean hasMessage();

        /**
         * <code>required bytes message = 5;</code>
         */
        com.google.protobuf.ByteString getMessage();
    }

    /**
     * Protobuf type {@code teleporter.integration.proto.KafkaProto}
     */
    public static final class KafkaProto extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:teleporter.integration.proto.KafkaProto)
            KafkaProtoOrBuilder {
        // Use KafkaProto.newBuilder() to construct.
        private KafkaProto(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private KafkaProto(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final KafkaProto defaultInstance;

        public static KafkaProto getDefaultInstance() {
            return defaultInstance;
        }

        public KafkaProto getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private KafkaProto(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            tId_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            com.google.protobuf.ByteString bs = input.readBytes();
                            bitField0_ |= 0x00000002;
                            topic_ = bs;
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            key_ = input.readBytes();
                            break;
                        }
                        case 32: {
                            bitField0_ |= 0x00000008;
                            partition_ = input.readInt32();
                            break;
                        }
                        case 42: {
                            bitField0_ |= 0x00000010;
                            message_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProto_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProto_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.class, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder.class);
        }

        public static com.google.protobuf.Parser<KafkaProto> PARSER =
                new com.google.protobuf.AbstractParser<KafkaProto>() {
                    public KafkaProto parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new KafkaProto(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<KafkaProto> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        public static final int TID_FIELD_NUMBER = 1;
        private com.google.protobuf.ByteString tId_;

        /**
         * <code>required bytes tId = 1;</code>
         */
        public boolean hasTId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required bytes tId = 1;</code>
         */
        public com.google.protobuf.ByteString getTId() {
            return tId_;
        }

        public static final int TOPIC_FIELD_NUMBER = 2;
        private java.lang.Object topic_;

        /**
         * <code>required string topic = 2;</code>
         */
        public boolean hasTopic() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string topic = 2;</code>
         */
        public java.lang.String getTopic() {
            java.lang.Object ref = topic_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    topic_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string topic = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTopicBytes() {
            java.lang.Object ref = topic_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                topic_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int KEY_FIELD_NUMBER = 3;
        private com.google.protobuf.ByteString key_;

        /**
         * <code>required bytes key = 3;</code>
         */
        public boolean hasKey() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required bytes key = 3;</code>
         */
        public com.google.protobuf.ByteString getKey() {
            return key_;
        }

        public static final int PARTITION_FIELD_NUMBER = 4;
        private int partition_;

        /**
         * <code>required int32 partition = 4;</code>
         */
        public boolean hasPartition() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required int32 partition = 4;</code>
         */
        public int getPartition() {
            return partition_;
        }

        public static final int MESSAGE_FIELD_NUMBER = 5;
        private com.google.protobuf.ByteString message_;

        /**
         * <code>required bytes message = 5;</code>
         */
        public boolean hasMessage() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>required bytes message = 5;</code>
         */
        public com.google.protobuf.ByteString getMessage() {
            return message_;
        }

        private void initFields() {
            tId_ = com.google.protobuf.ByteString.EMPTY;
            topic_ = "";
            key_ = com.google.protobuf.ByteString.EMPTY;
            partition_ = 0;
            message_ = com.google.protobuf.ByteString.EMPTY;
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            if (!hasTId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasTopic()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasKey()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasPartition()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMessage()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, tId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getTopicBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, key_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, partition_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBytes(5, message_);
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, tId_);
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getTopicBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, key_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(4, partition_);
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(5, message_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(teleporter.integration.protocol.proto.KafkaBuf.KafkaProto prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code teleporter.integration.proto.KafkaProto}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:teleporter.integration.proto.KafkaProto)
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProto_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProto_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.class, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder.class);
            }

            // Construct using teleporter.integration.proto.KafkaBuf.KafkaProto.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                tId_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000001);
                topic_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                key_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                partition_ = 0;
                bitField0_ = (bitField0_ & ~0x00000008);
                message_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProto_descriptor;
            }

            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto getDefaultInstanceForType() {
                return teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.getDefaultInstance();
            }

            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto build() {
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProto result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto buildPartial() {
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProto result = new teleporter.integration.protocol.proto.KafkaBuf.KafkaProto(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.tId_ = tId_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.topic_ = topic_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.key_ = key_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.partition_ = partition_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.message_ = message_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof teleporter.integration.protocol.proto.KafkaBuf.KafkaProto) {
                    return mergeFrom((teleporter.integration.protocol.proto.KafkaBuf.KafkaProto) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(teleporter.integration.protocol.proto.KafkaBuf.KafkaProto other) {
                if (other == teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.getDefaultInstance()) return this;
                if (other.hasTId()) {
                    setTId(other.getTId());
                }
                if (other.hasTopic()) {
                    bitField0_ |= 0x00000002;
                    topic_ = other.topic_;
                    onChanged();
                }
                if (other.hasKey()) {
                    setKey(other.getKey());
                }
                if (other.hasPartition()) {
                    setPartition(other.getPartition());
                }
                if (other.hasMessage()) {
                    setMessage(other.getMessage());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasTId()) {

                    return false;
                }
                if (!hasTopic()) {

                    return false;
                }
                if (!hasKey()) {

                    return false;
                }
                if (!hasPartition()) {

                    return false;
                }
                if (!hasMessage()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProto parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (teleporter.integration.protocol.proto.KafkaBuf.KafkaProto) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private com.google.protobuf.ByteString tId_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes tId = 1;</code>
             */
            public boolean hasTId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required bytes tId = 1;</code>
             */
            public com.google.protobuf.ByteString getTId() {
                return tId_;
            }

            /**
             * <code>required bytes tId = 1;</code>
             */
            public Builder setTId(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                tId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes tId = 1;</code>
             */
            public Builder clearTId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                tId_ = getDefaultInstance().getTId();
                onChanged();
                return this;
            }

            private java.lang.Object topic_ = "";

            /**
             * <code>required string topic = 2;</code>
             */
            public boolean hasTopic() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string topic = 2;</code>
             */
            public java.lang.String getTopic() {
                java.lang.Object ref = topic_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        topic_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string topic = 2;</code>
             */
            public com.google.protobuf.ByteString
            getTopicBytes() {
                java.lang.Object ref = topic_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    topic_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string topic = 2;</code>
             */
            public Builder setTopic(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                topic_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string topic = 2;</code>
             */
            public Builder clearTopic() {
                bitField0_ = (bitField0_ & ~0x00000002);
                topic_ = getDefaultInstance().getTopic();
                onChanged();
                return this;
            }

            /**
             * <code>required string topic = 2;</code>
             */
            public Builder setTopicBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                topic_ = value;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes key = 3;</code>
             */
            public boolean hasKey() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required bytes key = 3;</code>
             */
            public com.google.protobuf.ByteString getKey() {
                return key_;
            }

            /**
             * <code>required bytes key = 3;</code>
             */
            public Builder setKey(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                key_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes key = 3;</code>
             */
            public Builder clearKey() {
                bitField0_ = (bitField0_ & ~0x00000004);
                key_ = getDefaultInstance().getKey();
                onChanged();
                return this;
            }

            private int partition_;

            /**
             * <code>required int32 partition = 4;</code>
             */
            public boolean hasPartition() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required int32 partition = 4;</code>
             */
            public int getPartition() {
                return partition_;
            }

            /**
             * <code>required int32 partition = 4;</code>
             */
            public Builder setPartition(int value) {
                bitField0_ |= 0x00000008;
                partition_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required int32 partition = 4;</code>
             */
            public Builder clearPartition() {
                bitField0_ = (bitField0_ & ~0x00000008);
                partition_ = 0;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>required bytes message = 5;</code>
             */
            public boolean hasMessage() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>required bytes message = 5;</code>
             */
            public com.google.protobuf.ByteString getMessage() {
                return message_;
            }

            /**
             * <code>required bytes message = 5;</code>
             */
            public Builder setMessage(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000010;
                message_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bytes message = 5;</code>
             */
            public Builder clearMessage() {
                bitField0_ = (bitField0_ & ~0x00000010);
                message_ = getDefaultInstance().getMessage();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:teleporter.integration.proto.KafkaProto)
        }

        static {
            defaultInstance = new KafkaProto(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:teleporter.integration.proto.KafkaProto)
    }

    public interface KafkaProtosOrBuilder extends
            // @@protoc_insertion_point(interface_extends:teleporter.integration.proto.KafkaProtos)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        java.util.List<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto>
        getProtosList();

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        teleporter.integration.protocol.proto.KafkaBuf.KafkaProto getProtos(int index);

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        int getProtosCount();

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        java.util.List<? extends teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder>
        getProtosOrBuilderList();

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder getProtosOrBuilder(
                int index);
    }

    /**
     * Protobuf type {@code teleporter.integration.proto.KafkaProtos}
     */
    public static final class KafkaProtos extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:teleporter.integration.proto.KafkaProtos)
            KafkaProtosOrBuilder {
        // Use KafkaProtos.newBuilder() to construct.
        private KafkaProtos(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private KafkaProtos(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final KafkaProtos defaultInstance;

        public static KafkaProtos getDefaultInstance() {
            return defaultInstance;
        }

        public KafkaProtos getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private KafkaProtos(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                protos_ = new java.util.ArrayList<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            protos_.add(input.readMessage(teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.PARSER, extensionRegistry));
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    protos_ = java.util.Collections.unmodifiableList(protos_);
                }
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProtos_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProtos_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos.class, teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos.Builder.class);
        }

        public static com.google.protobuf.Parser<KafkaProtos> PARSER =
                new com.google.protobuf.AbstractParser<KafkaProtos>() {
                    public KafkaProtos parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new KafkaProtos(input, extensionRegistry);
                    }
                };

        @java.lang.Override
        public com.google.protobuf.Parser<KafkaProtos> getParserForType() {
            return PARSER;
        }

        public static final int PROTOS_FIELD_NUMBER = 1;
        private java.util.List<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto> protos_;

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        public java.util.List<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto> getProtosList() {
            return protos_;
        }

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        public java.util.List<? extends teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder>
        getProtosOrBuilderList() {
            return protos_;
        }

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        public int getProtosCount() {
            return protos_.size();
        }

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto getProtos(int index) {
            return protos_.get(index);
        }

        /**
         * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
         */
        public teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder getProtosOrBuilder(
                int index) {
            return protos_.get(index);
        }

        private void initFields() {
            protos_ = java.util.Collections.emptyList();
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            for (int i = 0; i < getProtosCount(); i++) {
                if (!getProtos(i).isInitialized()) {
                    memoizedIsInitialized = 0;
                    return false;
                }
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < protos_.size(); i++) {
                output.writeMessage(1, protos_.get(i));
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < protos_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, protos_.get(i));
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code teleporter.integration.proto.KafkaProtos}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:teleporter.integration.proto.KafkaProtos)
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProtosOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProtos_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProtos_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos.class, teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos.Builder.class);
            }

            // Construct using teleporter.integration.proto.KafkaBuf.KafkaProtos.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                    getProtosFieldBuilder();
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                if (protosBuilder_ == null) {
                    protos_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                } else {
                    protosBuilder_.clear();
                }
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return teleporter.integration.protocol.proto.KafkaBuf.internal_static_teleporter_integration_proto_KafkaProtos_descriptor;
            }

            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos getDefaultInstanceForType() {
                return teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos.getDefaultInstance();
            }

            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos build() {
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos buildPartial() {
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos result = new teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos(this);
                int from_bitField0_ = bitField0_;
                if (protosBuilder_ == null) {
                    if (((bitField0_ & 0x00000001) == 0x00000001)) {
                        protos_ = java.util.Collections.unmodifiableList(protos_);
                        bitField0_ = (bitField0_ & ~0x00000001);
                    }
                    result.protos_ = protos_;
                } else {
                    result.protos_ = protosBuilder_.build();
                }
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos) {
                    return mergeFrom((teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos other) {
                if (other == teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos.getDefaultInstance()) return this;
                if (protosBuilder_ == null) {
                    if (!other.protos_.isEmpty()) {
                        if (protos_.isEmpty()) {
                            protos_ = other.protos_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                        } else {
                            ensureProtosIsMutable();
                            protos_.addAll(other.protos_);
                        }
                        onChanged();
                    }
                } else {
                    if (!other.protos_.isEmpty()) {
                        if (protosBuilder_.isEmpty()) {
                            protosBuilder_.dispose();
                            protosBuilder_ = null;
                            protos_ = other.protos_;
                            bitField0_ = (bitField0_ & ~0x00000001);
                            protosBuilder_ =
                                    com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                                            getProtosFieldBuilder() : null;
                        } else {
                            protosBuilder_.addAllMessages(other.protos_);
                        }
                    }
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                for (int i = 0; i < getProtosCount(); i++) {
                    if (!getProtos(i).isInitialized()) {

                        return false;
                    }
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (teleporter.integration.protocol.proto.KafkaBuf.KafkaProtos) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private java.util.List<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto> protos_ =
                    java.util.Collections.emptyList();

            private void ensureProtosIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    protos_ = new java.util.ArrayList<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto>(protos_);
                    bitField0_ |= 0x00000001;
                }
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    teleporter.integration.protocol.proto.KafkaBuf.KafkaProto, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder, teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder> protosBuilder_;

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public java.util.List<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto> getProtosList() {
                if (protosBuilder_ == null) {
                    return java.util.Collections.unmodifiableList(protos_);
                } else {
                    return protosBuilder_.getMessageList();
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public int getProtosCount() {
                if (protosBuilder_ == null) {
                    return protos_.size();
                } else {
                    return protosBuilder_.getCount();
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto getProtos(int index) {
                if (protosBuilder_ == null) {
                    return protos_.get(index);
                } else {
                    return protosBuilder_.getMessage(index);
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder setProtos(
                    int index, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto value) {
                if (protosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureProtosIsMutable();
                    protos_.set(index, value);
                    onChanged();
                } else {
                    protosBuilder_.setMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder setProtos(
                    int index, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder builderForValue) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.set(index, builderForValue.build());
                    onChanged();
                } else {
                    protosBuilder_.setMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder addProtos(teleporter.integration.protocol.proto.KafkaBuf.KafkaProto value) {
                if (protosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureProtosIsMutable();
                    protos_.add(value);
                    onChanged();
                } else {
                    protosBuilder_.addMessage(value);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder addProtos(
                    int index, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto value) {
                if (protosBuilder_ == null) {
                    if (value == null) {
                        throw new NullPointerException();
                    }
                    ensureProtosIsMutable();
                    protos_.add(index, value);
                    onChanged();
                } else {
                    protosBuilder_.addMessage(index, value);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder addProtos(
                    teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder builderForValue) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.add(builderForValue.build());
                    onChanged();
                } else {
                    protosBuilder_.addMessage(builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder addProtos(
                    int index, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder builderForValue) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.add(index, builderForValue.build());
                    onChanged();
                } else {
                    protosBuilder_.addMessage(index, builderForValue.build());
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder addAllProtos(
                    java.lang.Iterable<? extends teleporter.integration.protocol.proto.KafkaBuf.KafkaProto> values) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    com.google.protobuf.AbstractMessageLite.Builder.addAll(
                            values, protos_);
                    onChanged();
                } else {
                    protosBuilder_.addAllMessages(values);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder clearProtos() {
                if (protosBuilder_ == null) {
                    protos_ = java.util.Collections.emptyList();
                    bitField0_ = (bitField0_ & ~0x00000001);
                    onChanged();
                } else {
                    protosBuilder_.clear();
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public Builder removeProtos(int index) {
                if (protosBuilder_ == null) {
                    ensureProtosIsMutable();
                    protos_.remove(index);
                    onChanged();
                } else {
                    protosBuilder_.remove(index);
                }
                return this;
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder getProtosBuilder(
                    int index) {
                return getProtosFieldBuilder().getBuilder(index);
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder getProtosOrBuilder(
                    int index) {
                if (protosBuilder_ == null) {
                    return protos_.get(index);
                } else {
                    return protosBuilder_.getMessageOrBuilder(index);
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public java.util.List<? extends teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder>
            getProtosOrBuilderList() {
                if (protosBuilder_ != null) {
                    return protosBuilder_.getMessageOrBuilderList();
                } else {
                    return java.util.Collections.unmodifiableList(protos_);
                }
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder addProtosBuilder() {
                return getProtosFieldBuilder().addBuilder(
                        teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.getDefaultInstance());
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder addProtosBuilder(
                    int index) {
                return getProtosFieldBuilder().addBuilder(
                        index, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.getDefaultInstance());
            }

            /**
             * <code>repeated .teleporter.integration.proto.KafkaProto protos = 1;</code>
             */
            public java.util.List<teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder>
            getProtosBuilderList() {
                return getProtosFieldBuilder().getBuilderList();
            }

            private com.google.protobuf.RepeatedFieldBuilder<
                    teleporter.integration.protocol.proto.KafkaBuf.KafkaProto, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder, teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder>
            getProtosFieldBuilder() {
                if (protosBuilder_ == null) {
                    protosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
                            teleporter.integration.protocol.proto.KafkaBuf.KafkaProto, teleporter.integration.protocol.proto.KafkaBuf.KafkaProto.Builder, teleporter.integration.protocol.proto.KafkaBuf.KafkaProtoOrBuilder>(
                            protos_,
                            ((bitField0_ & 0x00000001) == 0x00000001),
                            getParentForChildren(),
                            isClean());
                    protos_ = null;
                }
                return protosBuilder_;
            }

            // @@protoc_insertion_point(builder_scope:teleporter.integration.proto.KafkaProtos)
        }

        static {
            defaultInstance = new KafkaProtos(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:teleporter.integration.proto.KafkaProtos)
    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_teleporter_integration_proto_KafkaProto_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_teleporter_integration_proto_KafkaProto_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_teleporter_integration_proto_KafkaProtos_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_teleporter_integration_proto_KafkaProtos_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n(src/main/resources/proto/kafka_buf.pro" +
                        "to\022\034teleporter.integration.proto\"Y\n\nKafk" +
                        "aProto\022\013\n\003tId\030\001 \002(\014\022\r\n\005topic\030\002 \002(\t\022\013\n\003ke" +
                        "y\030\003 \002(\014\022\021\n\tpartition\030\004 \002(\005\022\017\n\007message\030\005 " +
                        "\002(\014\"G\n\013KafkaProtos\0228\n\006protos\030\001 \003(\0132(.tel" +
                        "eporter.integration.proto.KafkaProto"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_teleporter_integration_proto_KafkaProto_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_teleporter_integration_proto_KafkaProto_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_teleporter_integration_proto_KafkaProto_descriptor,
                new java.lang.String[]{"TId", "Topic", "Key", "Partition", "Message",});
        internal_static_teleporter_integration_proto_KafkaProtos_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_teleporter_integration_proto_KafkaProtos_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_teleporter_integration_proto_KafkaProtos_descriptor,
                new java.lang.String[]{"Protos",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
