// automatically generated by the FlatBuffers compiler, do not modify

package teleporter.integration.cluster.rpc.fbs.generate;

public final class Role {
  private Role() { }
  public static final byte CLIENT = 0;
  public static final byte SERVER = 1;
  public static final byte None = 2;

  public static final String[] names = { "CLIENT", "SERVER", "None", };

  public static String name(int e) { return names[e]; }
}

